name: Hotbar
main: ARTulloss\Hotbar\Hotbar
api: [3.0.0]
version: 1.1.3
author: ARTulloss
description: Hotbar Items!<<<<<<< HEAD
=======
description: Hotbar Items!
>>>>>>> ec477f01f1a5d6ee33cc3882f6e73854b62b4001
