---
Items:
  world:
    §rDefault Config!:
      Item: "399:0:1"
      Slot: 0
      Lore:
      - §r§9This is the default configuration!
      Commands:
      # Example:
      # - command goes here@type of executor@op (true) or not op (false)

      - say Your name is {player}!@player@true

      # Types of executors

      # Player
      # Here
      # Everyone
      # Console
      # Player's name, for example ARTulloss (my ign)

      # Replacable stuff

      # {player}  IGN
      # {tag}     Name tag
      # {level}   Player level
      # {x}       Player X
      # {y}       Player Y
      # {z}       Player Z
      # {rx}      Player X (Rounded)
      # {ry}      Player Y (Rounded)
      # {rz}      Player Z (Rounded)

      Enchant: true
Locked Inventory:
- world
Cooldown: 1
...
